apiVersion: v1
kind: Service
metadata:
  name: pixiu-localstorage-service
  namespace: kube-system
spec:
  ports:
    - name: tcp-8443
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: pixiu-ls-controller
  type: ClusterIP
