apiVersion: storage.k8s.io/v1 # 给这些yaml增加注释，方便理解
kind: StorageClass # 创建一个存储类
metadata:
  name: pixiu-localstorage # 指定存储类名称
mountOptions:
  - owner=caoyingjunz # 指定挂载选项为指定用户
parameters: # 指定参数
  project: pixiu # 指定项目名称
provisioner: localstorage.csi.caoyingjunz.io # 指定 CSI 驱动名称
reclaimPolicy: Delete # 指定回收策略
volumeBindingMode: WaitForFirstConsumer # 指定绑定模式

# 总结：CSI 驱动的创建，需要创建 CSIDriver 和 StorageClass 两个资源，其中 CSIDriver 用于指定 CSI 驱动的名称，StorageClass 用于指定 CSI 驱动的名称、挂载选项、参数、回收策略和绑定模式等。