kind: LocalStorage
apiVersion: storage.caoyingjunz.io/v1
metadata:
  annotations:
    # 自定义可分配的存储容量, 在 path 模式下生效
    volume.caoyingjunz.io/node-size: 360Gi
  name: ls-pixiu-node
spec:
  node: pixiu-node
  # 指定 path 模式时的 volume 文件夹
  path:
    volumeDir: /data
  # 指定 vlm 模式时的磁盘配置
  lvm:
    volumeGroup: pixiu
    disks:
      - name: pixiu-disk
