apiVersion: v1
kind: Service
metadata:
  name: pixiu-localstorage-service
  namespace: kube-system
spec:
  ports:
    - name: tcp-8443
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: pixiu-ls-controller
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ls-scheduler-extender
  namespace: kube-system
spec:
  ports:
    - name: tcp-8090
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: ls-scheduler-extender
  type: ClusterIP
