apiVersion: v1
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    extenders:
      - urlPrefix: http://ls-scheduler-extender.kube-system:8090/localstorage-scheduler
        filterVerb: filter
        prioritizeVerb: prioritize
        enableHTTPS: false
        weight: 5
        nodeCacheCapable: true
        ignorable: false
kind: ConfigMap
metadata:
  name: ls-scheduler-extender-config
  namespace: kube-system
