apiVersion: v1
kind: Service
metadata:
  name: pixiu-ls-controller
  namespace: kube-system
spec:
  ports:
    - name: tcp-8443
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: pixiu-ls-controller
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pixiu-ls-scheduler
  namespace: kube-system
spec:
  ports:
    - name: tcp-8090
      nodePort: 30666
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: pixiu-ls-scheduler
  type: NodePort
