---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pixiu-ls-mutating-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW8rZ0F3SUJBZ0lVRURBYzkwa1dVUXN5UmJodThlUitzOFlHR3Y4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURWZNQjBHQTFVRUF3d1djR2w0YVhVdGJITXRZMjl1ZEhKdmJHeGxjaUJEUVRBZ0Z3MHlNekEzTVRNeApNekl5TWpaYUdBOHlNVEl6TURZeE9URXpNakl5Tmxvd0xqRXNNQ29HQTFVRUF3d2pjR2w0YVhVdGJITXRZMjl1CmRISnZiR3hsY2k1cmRXSmxMWE41YzNSbGJTNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUN5d1dZcHFGekFlaS9oL2pBMjFFOWJIZ1NhcjJBTnJNQlcrRk5vOUJCMG9FLytXZkpRejRlaQowVnNuWGpVdTNHTm5ZR1BVMU81ZTdibmtEYjRhOGRremUyZzc1aEFWZ25ldXJFSERuemVVdkpHdnBOZ3dMSFNHClprbERSQkJoTDJJTEVVZkl5bWNnV21mZGtFL2d2M1dTcFowdWdZSnYrR1F1ZmFiNW5lT3ZZYWpyS3pOZFIzb1MKZ0pyUDNzMkNUdU1lcnNIdGtsVWxhZlZNK3ltNlhWSjZXV25veEE3akhUYjJ5OGNkSFdYTmZYVjFuUlhONENkeApXRWFubk9SS0lIc3l4cXdzUXRGYUx6R0hzekhiVTA5VzJYeTNIZ1gxVDFsQzBCSFNlYUdjNHV6cEpQK3VSRzMwCk1GSXNTclhSY2RRckNSakszM0VJWW1TVWVRdkd0Um03QWdNQkFBR2pnY2N3Z2NRd0NRWURWUjBUQkFJd0FEQUwKQmdOVkhROEVCQU1DQmVBd2FnWURWUjBSQkdNd1lZSVRjR2w0YVhVdGJITXRZMjl1ZEhKdmJHeGxjb0lmY0dsNAphWFV0YkhNdFkyOXVkSEp2Ykd4bGNpNXJkV0psTFhONWMzUmxiWUlqY0dsNGFYVXRiSE10WTI5dWRISnZiR3hsCmNpNXJkV0psTFhONWMzUmxiUzV6ZG1PSEJIOEFBQUV3SFFZRFZSME9CQllFRkwwdFZSOGNiTnBTWnF6K3E5ZjAKdWlERXV3eEhNQjhHQTFVZEl3UVlNQmFBRlB4T1FkcmRuOXJjSkVVa3VLRVprWVFBRElXaE1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUFpeG03cEZvOHU2S2FnL0NoMndjaGtTRHVUZXNqRlNDQVpsc01JTkk3dFptTnFadVliCmVJeEZUSEorKzkrVmlNRXJCQ0xhanU4VVorUExlN2p4Mm01UGYvbEY0NDZRdi9EUkhuYlVlS1d6NkRXamhBTngKMFJjalpRVXNMZE9BaUxtYmZvOTBjZnorcjc3KzduZzN6NitPSlpPSCtYWnVOUFM1Z2lUQTdYMmpLSUFQazJCcwpNcGFscVpETElFczFWM3BTaFdCTFZYa1FZeEFBUGJRaG1VTHJUMDNXdmRUOTZEeURiM0gvcHFhb0ZsK0RPMCt3CktwdFZQNW5vVVg1eVRWSG5pMnRldkttbHZwb0Z4RUVDMmFnd3RNeGpaK0EzUGV6YzAzVnhyZllzb0cyNU4xN3IKaGp4STJBQStCZ2g0dm1GRzkvM2E0VE1nbHVWOGlDa0dqQUp2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: pixiu-ls-controller
        namespace: kube-system
        path: /mutate-v1-localstorage
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: webhook.pixiu.io
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - storage.caoyingjunz.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - localstorages
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pixiu-ls-validating-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW8rZ0F3SUJBZ0lVRURBYzkwa1dVUXN5UmJodThlUitzOFlHR3Y4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURWZNQjBHQTFVRUF3d1djR2w0YVhVdGJITXRZMjl1ZEhKdmJHeGxjaUJEUVRBZ0Z3MHlNekEzTVRNeApNekl5TWpaYUdBOHlNVEl6TURZeE9URXpNakl5Tmxvd0xqRXNNQ29HQTFVRUF3d2pjR2w0YVhVdGJITXRZMjl1CmRISnZiR3hsY2k1cmRXSmxMWE41YzNSbGJTNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUN5d1dZcHFGekFlaS9oL2pBMjFFOWJIZ1NhcjJBTnJNQlcrRk5vOUJCMG9FLytXZkpRejRlaQowVnNuWGpVdTNHTm5ZR1BVMU81ZTdibmtEYjRhOGRremUyZzc1aEFWZ25ldXJFSERuemVVdkpHdnBOZ3dMSFNHClprbERSQkJoTDJJTEVVZkl5bWNnV21mZGtFL2d2M1dTcFowdWdZSnYrR1F1ZmFiNW5lT3ZZYWpyS3pOZFIzb1MKZ0pyUDNzMkNUdU1lcnNIdGtsVWxhZlZNK3ltNlhWSjZXV25veEE3akhUYjJ5OGNkSFdYTmZYVjFuUlhONENkeApXRWFubk9SS0lIc3l4cXdzUXRGYUx6R0hzekhiVTA5VzJYeTNIZ1gxVDFsQzBCSFNlYUdjNHV6cEpQK3VSRzMwCk1GSXNTclhSY2RRckNSakszM0VJWW1TVWVRdkd0Um03QWdNQkFBR2pnY2N3Z2NRd0NRWURWUjBUQkFJd0FEQUwKQmdOVkhROEVCQU1DQmVBd2FnWURWUjBSQkdNd1lZSVRjR2w0YVhVdGJITXRZMjl1ZEhKdmJHeGxjb0lmY0dsNAphWFV0YkhNdFkyOXVkSEp2Ykd4bGNpNXJkV0psTFhONWMzUmxiWUlqY0dsNGFYVXRiSE10WTI5dWRISnZiR3hsCmNpNXJkV0psTFhONWMzUmxiUzV6ZG1PSEJIOEFBQUV3SFFZRFZSME9CQllFRkwwdFZSOGNiTnBTWnF6K3E5ZjAKdWlERXV3eEhNQjhHQTFVZEl3UVlNQmFBRlB4T1FkcmRuOXJjSkVVa3VLRVprWVFBRElXaE1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUFpeG03cEZvOHU2S2FnL0NoMndjaGtTRHVUZXNqRlNDQVpsc01JTkk3dFptTnFadVliCmVJeEZUSEorKzkrVmlNRXJCQ0xhanU4VVorUExlN2p4Mm01UGYvbEY0NDZRdi9EUkhuYlVlS1d6NkRXamhBTngKMFJjalpRVXNMZE9BaUxtYmZvOTBjZnorcjc3KzduZzN6NitPSlpPSCtYWnVOUFM1Z2lUQTdYMmpLSUFQazJCcwpNcGFscVpETElFczFWM3BTaFdCTFZYa1FZeEFBUGJRaG1VTHJUMDNXdmRUOTZEeURiM0gvcHFhb0ZsK0RPMCt3CktwdFZQNW5vVVg1eVRWSG5pMnRldkttbHZwb0Z4RUVDMmFnd3RNeGpaK0EzUGV6YzAzVnhyZllzb0cyNU4xN3IKaGp4STJBQStCZ2g0dm1GRzkvM2E0VE1nbHVWOGlDa0dqQUp2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: pixiu-ls-controller
        namespace: kube-system
        path: /validate-v1-localstorage
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: webhook.pixiu.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - storage.caoyingjunz.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - localstorages
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
